"""Phase 2 — the historical-events layer, generated by Claude and cached to disk.

For each (country, decade) present in the book corpus we ask Claude for a short,
structured list of major historical events. Results are cached as JSON so we only
pay for generation once. Uses the cheaper/faster model (Haiku) since this is bulk,
factual work; the expensive synthesis model is reserved for answering.

We ask for raw JSON in the prompt and extract it, so this works on both the CLI
and SDK backends (the CLI has no structured-output parameter).
"""
from __future__ import annotations

import json
import re

from . import config
from .ingest import load_books
from .llm import get_llm

_SYSTEM = (
    "You are a historian assembling concise timelines to contextualize literature. "
    "Given a country and a decade, list the major historical events and conditions "
    "(political, social, economic, cultural) of that place and period that a literary "
    "scholar would cite when discussing novels written then. Be factual and specific."
)

_JSON_SPEC = (
    'Respond with ONLY a JSON object (no markdown fences, no prose) of the form:\n'
    '{"events": [{"year": <int>, "title": <str>, "summary": <str>, '
    '"kind": "political|social|economic|cultural|war|other"}]}'
)

_FENCE_RE = re.compile(r"^```[a-zA-Z]*\n?|\n?```$")


def _extract_json(text: str) -> dict:
    text = _FENCE_RE.sub("", text.strip())
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"no JSON object in model output: {text[:200]}")
    return json.loads(text[start:end + 1])


def _cache_path(country: str, decade: int):
    safe = "".join(c if c.isalnum() else "_" for c in country) or "unknown"
    return config.HISTORY_DIR / f"{safe}_{decade}.json"


def _pairs_from_corpus() -> set[tuple[str, int]]:
    pairs = set()
    for b in load_books():
        if b["country"] and b["decade"]:
            pairs.add((b["country"], int(b["decade"])))
    return pairs


def _generate(llm, country: str, decade: int) -> dict:
    user = (
        f"Country: {country}\nDecade: {decade}s ({decade}–{decade + 9})\n\n"
        "List 6–12 key events/conditions for this place and decade. "
        "Write event titles in English with the original place name where relevant.\n\n"
        + _JSON_SPEC
    )
    text = llm.complete(_SYSTEM, user, model=config.HISTORY_MODEL, max_tokens=2000)
    return _extract_json(text)


def run(force: bool = False) -> int:
    config.ensure_dirs()
    llm = get_llm()
    pairs = sorted(_pairs_from_corpus())
    print(f"Generating history via '{llm.name}' backend "
          f"({config.HISTORY_MODEL}) for {len(pairs)} (country, decade) pairs...")
    made = 0
    for country, decade in pairs:
        path = _cache_path(country, decade)
        if path.exists() and not force:
            continue
        try:
            data = _generate(llm, country, decade)
        except Exception as e:  # noqa: BLE001 — keep going on a single failure
            print(f"  ! {country} {decade}s failed: {e}")
            continue
        data["country"], data["decade"] = country, decade
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2),
                        encoding="utf-8")
        made += 1
        print(f"  + {country} {decade}s  ({len(data.get('events', []))} events)")

    print(f"History layer: {made} new timelines; {len(pairs)} total in corpus.")
    return made


def load_events() -> list[dict]:
    """Flatten all cached timelines into individual event records."""
    out = []
    for path in sorted(config.HISTORY_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        country, decade = data.get("country"), data.get("decade")
        for ev in data.get("events", []):
            out.append({**ev, "country": country, "decade": decade})
    return out
