"""Phase 2b — per-book literary-historical profiles, generated by Claude.

Each review is rich in plot/characters but thin on *historical* connective
tissue, and we only know the *publication* year — not when/where the story is
*set*. This pass asks Claude to produce a structured profile per book that adds
exactly the signal the history<->literature bridge needs:

  - setting_period / setting_place: the story's own time & place (often != the
    publication year — a 1960 novel can be set during WWI). This is the key fix.
  - themes, historical_backdrop: what the work engages with.
  - plot_synopsis, characters: a cleaner, fuller version than the raw review.
  - confidence: the model's own familiarity with the work, so downstream
    answers can weight accordingly.

Grounded in the review text; uses Claude's knowledge of the work. Prompt-based
JSON so it runs on both the CLI and SDK backends. Cached to data/profiles/.
"""
from __future__ import annotations

import json
import re

from . import config
from .ingest import load_books
from .llm import get_llm
from .utils import decade_of

_SYSTEM = (
    "You are a literary scholar building structured metadata to connect novels to "
    "the history of their time. You know the canonical works of world literature. "
    "Ground your answer in the provided review, but use your own knowledge of the "
    "work to fill in setting, themes, and historical context. If you are not "
    "familiar with the specific work, say so via the confidence field and rely only "
    "on the review — do not invent specifics."
)

_JSON_SPEC = (
    'Respond with ONLY a JSON object (no markdown fences, no prose):\n'
    '{\n'
    '  "setting_place": <str: where the story is set, English>,\n'
    '  "setting_start": <int year or null>,\n'
    '  "setting_end": <int year or null>,\n'
    '  "themes": [<str>, ...],\n'
    '  "historical_backdrop": <str: real events/conditions the work depicts or '
    'alludes to>,\n'
    '  "plot_synopsis": <str: 2-4 sentences>,\n'
    '  "characters": [{"name": <str>, "role": <str>}, ...],\n'
    '  "confidence": "high" | "medium" | "low"\n'
    '}'
)

_FENCE_RE = re.compile(r"^```[a-zA-Z]*\n?|\n?```$")


def _extract_json(text: str) -> dict:
    text = _FENCE_RE.sub("", text.strip())
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"no JSON object in model output: {text[:200]}")
    return json.loads(text[start:end + 1])


def _cache_path(slug: str):
    return config.PROFILES_DIR / f"{slug}.json"


def _grounding(book: dict) -> str:
    chars = "; ".join(f"{c['name']}: {c['desc']}" for c in book["characters"][:15])
    return (
        f"Title (fa): {book['title_fa']}\n"
        f"Original/EN title: {book['title_en']}\n"
        f"Author: {book['author']}\n"
        f"Publication year: {book['year']}\n"
        f"Author's country: {book['country']}\n"
        f"Genre: {book['genre']}\n"
        f"Characters from the review: {chars}\n\n"
        f"Review excerpt:\n{book['body'][:2500]}"
    )


def _generate(llm, book: dict) -> dict:
    user = (
        "Build a literary-historical profile for this book.\n\n"
        + _grounding(book) + "\n\n" + _JSON_SPEC
    )
    text = llm.complete(_SYSTEM, user, model=config.PROFILE_MODEL, max_tokens=1500)
    return _extract_json(text)


def setting_midpoint(profile: dict, fallback_year: int | None) -> int | None:
    """The story's representative year — used so temporal filters match story-time."""
    s, e = profile.get("setting_start"), profile.get("setting_end")
    if isinstance(s, int) and isinstance(e, int):
        return (s + e) // 2
    if isinstance(s, int):
        return s
    return fallback_year


def run(force: bool = False) -> int:
    config.ensure_dirs()
    llm = get_llm()
    books = load_books()
    print(f"Generating profiles via '{llm.name}' backend ({config.PROFILE_MODEL}) "
          f"for {len(books)} books...")
    made = 0
    for b in books:
        path = _cache_path(b["slug"])
        if path.exists() and not force:
            continue
        try:
            prof = _generate(llm, b)
        except Exception as e:  # noqa: BLE001 — keep going on a single failure
            print(f"  ! {b['slug']} failed: {e}")
            continue
        prof["slug"] = b["slug"]
        path.write_text(json.dumps(prof, ensure_ascii=False, indent=2),
                        encoding="utf-8")
        made += 1
        sp = prof.get("setting_place", "?")
        print(f"  + {b['slug'][:48]:48}  set in {sp} "
              f"[{prof.get('confidence')}]")

    print(f"Profiles: {made} new; {len(books)} books total.")
    return made


def load_profiles() -> dict[str, dict]:
    out = {}
    for path in sorted(config.PROFILES_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        out[data["slug"]] = data
    return out
